### ISSUE TITLE
Nice work. Release?

### ISSUE THREAD

**Issue by mindplay-dk** [pragmatrix/Promise#5]
This is the cleanest, simplest implementation of Promises/A+ I've seen in TypeScript so far.

According to [this page](https://www.nuget.org/packages/Promise.TypeScript/1.0.0-rc) you made several releases, up to 1.0-rc, one year ago...

How come a 1.0.0 was never released? Is there a problem? Does the project need help?

And how come no tags were ever applied here on GitHub? It's not clear from looking at the GitHub repo whether this is considered stable or complete.

Let me know if I can help.

**Comment by pragmatrix** [comment]
Thanks @mindplay-dk !

I've never released a new version, because I wasn't using this library anymore and had near zero feedback so far. Therefore I have no idea about the actual quality it represents.

From the top of my head, _Promise_ would need help in the following areas:

- Evaluate if there better [DefinitelyTyped](https://github.com/borisyankov/DefinitelyTyped) supported JavaScript alternatives? The latest TypeScript compiler most certainly supports generic type propagation in definition files as well (which was not the case when I started this implementation, and also was one of primary reasons why I started it) .
- Check if it compiles with the current TypeScript compiler and if all test cases pass.
- Clarify if exception handling is required? Must exception handling be supported before an initial release? I think so.
- Clarify if it complies with the latest Promises/A+ specification, and if not, point out the differences in the README file.

Needless to say, I am open for suggestions and appreciate pull requests.
